import { Message, MessagePayload, ApplicationCommandType, Locale, APIInteractionGuildMember, GuildMember, PermissionsBitField, ApplicationCommandOptionType, User, Attachment, InteractionEditReplyOptions, InteractionReplyOptions } from 'discord.js';
import { TDBIInteractions } from '../Interaction';
import { DBI } from '../../DBI';
import { NamespaceEnums } from "../../../generated/namespaceData";
export declare class FakeMessageInteraction {
    dbi: DBI<NamespaceEnums>;
    message: Message;
    commandMessage: Message;
    locale: string;
    usedPrefix: string;
    channelId: string;
    commandName: string;
    appPermissions: any;
    applicationId: string;
    channel: any;
    command: any;
    commandGuildId: string;
    commandId: any;
    commandType: ApplicationCommandType.ChatInput;
    deferred: boolean;
    client: any;
    createdAt: Date;
    ephemeral: boolean;
    createdTimestamp: number;
    guild: any;
    guildId: string;
    guildLocale: Locale;
    id: string;
    user: User;
    private repliedMessage;
    private lastFollowUp;
    member: GuildMember | APIInteractionGuildMember;
    memberPermissions: Readonly<PermissionsBitField>;
    parsedArgs: Map<string, FakeMessageInteractionArgument>;
    args: import("plsargs/src/Result").Result;
    usedCommandName: string;
    fullCommandName: string;
    options: any;
    dbiChatInput: TDBIInteractions<NamespaceEnums>;
    dbiChatInputOptions: any[];
    fake: boolean;
    _hoistedOptions: any;
    _initialized: boolean;
    _lastAction: string | undefined;
    constructor(dbi: DBI<NamespaceEnums>, message: Message, chatInput: TDBIInteractions<NamespaceEnums>, locale: string, commandName: string, usedPrefix: string);
    init(): void;
    _hoistedOptionsInit(): void;
    private getRawOptionValue;
    private getClonedDBIOption;
    inGuild(): boolean;
    deferReply(options: any): Promise<any>;
    deleteReply(): Promise<void>;
    followUp(content: string | MessagePayload): Promise<Message<boolean>>;
    editReply(content: string | MessagePayload | InteractionEditReplyOptions): Promise<Message<boolean>>;
    reply(content: string | MessagePayload | InteractionReplyOptions): Promise<any>;
    awaitModalSubmit(): Promise<void>;
    fetchReply(): Promise<Message<boolean>>;
    isAnySelectMenu(): boolean;
    isAutocomplete(): boolean;
    isButton(): boolean;
    isChannelSelectMenu(): boolean;
    isChatInputCommand(): boolean;
    isCommand(): boolean;
    isContextMenuCommand(): boolean;
    isMentionableSelectMenu(): boolean;
    isMessageComponent(): boolean;
    isMessageContextMenuCommand(): boolean;
    isModalSubmit(): boolean;
    isRepliable(): boolean;
    isRoleSelectMenu(): boolean;
    isStringSelectMenu(): boolean;
    isUserContextMenuCommand(): boolean;
    isUserSelectMenu(): boolean;
    isSelectMenu(): boolean;
}
interface FakeMessageInteractionArgument {
    type: ApplicationCommandOptionType;
    value: any;
    attachment?: Attachment;
    name: string;
}
export {};
//# sourceMappingURL=FakeMessageInteraction.d.ts.map
